### ISSUE TITLE
Update nickytests blog

### ISSUE THREAD

**Issue by Nicolasa123** [ChristoWolf/awesome-testing-blogs#14]
Hey!

Awesome list you got here :D

Could you change the domain for my blog? nickytests.blogspot.com

I now blog at nicolalindgren.com and moved all my posts there.

**Comment by ChristoWolf** [comment]
Hey @Nicolasa123!

Thanks for the kudos, this really means a lot to me coming from you :)

Of course, I will update the URL as soon as I have time.
Thanks for letting me know!

**Comment by ChristoWolf** [comment]
@Nicolasa123: Done :)
