### ISSUE TITLE
Suggestion for a new QA focused blog

### ISSUE THREAD

**Issue by Crypted39** [ChristoWolf/awesome-testing-blogs#34]
Hey there friends. I recently started a blog website focused on Quality Assurance and I got a suggestion from Reddit that it might fit into this list. By its content, it would fit into the Others section since my focus is on covering different QA topics. 

This is the link to the blog: https://www.thegreenreport.blog/

Let me know what you think. 

Best regards

**Comment by ChristoWolf** [comment]
Hi @Crypted39!

Thanks for the suggestion, looks great and interesting on first glance.
I'll check it out a bit more (and might subscribe) and I'll let you know as soon as I can.

Thanks also for the section suggestion.
If you have an idea how your entry could be better shown/categorized by improving the section layout and categorization, please let me know!

**Comment by ChristoWolf** [comment]
@Crypted39: I have added your blog, do you want to check out the change (#35)?

**Comment by Crypted39** [comment]
Thank you @ChristoWolf! I looked at the PR and the description sounds good.

**Comment by ChristoWolf** [comment]
Cool, thanks @Crypted39!
