### ISSUE TITLE
Add ceedling webpage and other blog

### ISSUE THREAD

**Issue by arbMerl** [ChristoWolf/awesome-testing-blogs#38]
TDD for embedded systems -> http://www.throwtheswitch.org/
Blog of one of the founders of throwtheswitch with TDD content and ceedling stuff -> http://vandervoord.net/

**Comment by ChristoWolf** [comment]
Hi @arbMerl!

Thanks for the suggestions.

If you want, you are of course welcome to create PR with your suggested changes, just let me know.

**Comment by ChristoWolf** [comment]
Resolved by #39.
